### ISSUE TITLE
error on request is not being forwarded

### ISSUE THREAD

**Issue by kesla** [FdezRomero/request-image-size#3]
https://github.com/FdezRomero/request-image-size/blob/master/index.js#L65 means that running `requestImageSize('http://server-that-is-temporarly-down.com/image.jpg', cb)` will not call cb with an error.

**Comment by FdezRomero** [comment]
Sorry for the super late fix! I refactored the code to return the request error to the callback and to prevent calling it twice (that's why it had a `noop` function there).
