### ISSUE TITLE
image-size needs to be updated

### ISSUE THREAD

**Issue by ryanscottaudio** [FdezRomero/request-image-size#4]
The maintainers of the `image-size` package have made updates, but because they're running a major version of 0, the minor version has to be bumped up for the latest versions of the package to automatically install.

**Comment by ryanscottaudio** [comment]
https://github.com/FdezRomero/request-image-size/pull/5

**Comment by FdezRomero** [comment]
Fixed in version 1.3.0, thanks! 👍
